_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 17
                - 18
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.5
            "6": 4.46.0
            "8":
                - 2
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
